### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by mihu**
This is mostly complete python3 support. Tests are passing on python2 and on python3.

On my testing rdb the python2 json dump is as fast as before and the output is the same. The python3 version is able to parse the rdb, unfortunatelly, custom json serializer in `callbacks.py` is unable to cope correctly with the serialization of my crazy named keys. From my point of view, this part should be eradicated in favour of standard json serializer.

### CODE REVIEW

**Comment by oranagra** [comment]
thanks.
from my understanding the "crazy named keys" is a separate problem and we can handle it separately later. we need to make sure there was no good reason why @sripathikrishnan didn't use the python native JSON.
i also see that Travis tests are failing.
@amotzg can you please take a look.

**Comment by amotzg** [comment]
Test are running successfully on my side.
Travis logs show it fails on installing from requirements.txt. We have an old version of redis-py declared there, redis-py now support python3. There is also the WSGI reference implementation, which (AFAIK) does not have python3 support. I don't see any reference to wsgiref on the project, so the most simple solution is probably to drop wsgiref and bump redis-py version.
More generally, as far as I can find, redis-py is only used on some of the tests code that is not active when testing with setup.py. So we have a requirements.txt file that is used only for tests that we usually (or never) don't run. It might be a better option to drop requirements.txt all together, and only use setup.py *_requires keys for declaring dependencies.

To say more about the actual PR I'll need to read deeper, but it generally looks like lots of good work on the right direction.

**Comment by oranagra** [comment]
@mihu if you don't see any problem with amotz's suggestion, let's take the cleaner (more aggressive) one and use setup.py fields instead of requirements.txt (and bump redis-py version). 

thank you both.

**Comment by mihu** [comment]
@oranagra I'm ok with that. Should it be part of this PR?

**Comment by oranagra** [comment]
@mihu  yeah if you can.., let's see that Travis status is fixed.

**Comment by oranagra** [comment]
Thanks. Merging.

**Pull request merged**
