### PR TITLE
fix report template generation

### LINKED ISSUE #42: Reporting HTML template not included in PyPI download.
I suspect that's because it doesn't match anything in MANIFEST.in and so isn't included in the source distribution file.

### PR DESCRIPTION
**Pull request by izakp**
Fixes two issues in current master:
-  `redis-profiler` command does not create outfile (only prints out html variable)
- report.html.template is not included by setup.py when running pip install

closes #42

### CODE REVIEW

**Comment by oranagra** [comment]
this isn't yet merged to this repo

**Comment by izakp** [comment]
@oranagra why did you repoen this?  It's been almost two years since I submitted this.  If you're not going to merge it I will close it.

**Comment by oranagra** [comment]
Hi, I opened it since I understand the problem is not fixed yet it this repository. And I intend to merge it. 
I'm sorry, this project wasn't maintained for a very long time, and since I "took over" (with @amotzg help) there has been tremendous progress. 
However, we both have "day jobs" and are doing this when we have spare time. 
In order to merge any PR, there is the need to invest at least a minimal amount of time to reproduce the problem, test the fix, and review the code. 
Please be patient.

**Comment by izakp** [comment]
@oranagra thanks for explaining the situation.  If you do have the intention of merging this, then that's wonderful and I'll leave it open.  I had just given up on it and have been going through my account, cleaning up old PRs.

**Comment by oranagra** [comment]
@hodgestar @izakp new version released into pypi, let me know if you see any problems.
thanks.

**Pull request merged**
