### PR TITLE
add support for rdb v9 (redis 5.0) and memory analysis of streams #128

### PR DESCRIPTION
**Pull request by oranagra**
other changes:
* adding both streams and modules to callbacks (with minimal info)
  at least providing an indication that the key exists.
* adding LRU and LFU metadata from RDBv9 if exists.
* start_module callback was missing info dict for metadata.
* supporting module AUX data (out of keyspace module data)
* module filtering was inefficient (called read_module rather than skip_module)
* tests and minor test suite improvement

### CODE REVIEW

**Comment by oranagra** [comment]
@sripathikrishnan please give this a quick look.
I did do a code review these changes internally, but let me know if there's something you wanna change.

Please note that this commit only lays the foundations for parsing of streams and RDBv9, but it does not yet provide a real look into the streams data since i didn't add the ability to decode listpacks. (this is out of my current scope, so i leave this for some future work)

Also note that the memory estimation is not very accurate since the only way to really compute the radix tree memory consumption is to build a redix tree and count the nodes.

**Comment by sripathikrishnan** [comment]
I will review this in detail in a day, but I had one concern. The original intent of the callback was to have functions familiar to end user. The `stream_listpack` callback method violates this principle, and I wasn't sure if that was a good thing. Especially since sooner or later we will add support for parsing the listpack itself - and then this method would become useless. Since the callback is the public interface - it will be difficult to delete it later on.

Perhaps we just delete that callback method right now, but commit rest of the parsing logic?

FYI - as part of https://github.com/sripathikrishnan/redis-rdb-tools/issues/132 - I realized that the current callback is ill suited to create a stream of RESTORE commands. I am thinking of adding another type of callback - one that explicitly requests for internal objects.

**Comment by oranagra** [comment]
@sripathikrishnan i think the parser can provide 3 levels of callbacks, so that each implementation of the callback can decide which one it listens to.
1) high level per item callbacks such as HSET and LPUSH
2) low level bytes buffer payload of each key, with which you can send RESTORE command.
3) medium level per ziplist / listpack callbacks, these are useful in order to easily compute the memory footprint in many cases. (estimating memory footprint of a ziplist from individual items, is both complicated and possibly inaccurate)

so for instance, the default implementation of listpack or ziplist can be one that unpacks the listpack or ziplist and calls individual HSET / LPUSH / XADD callbacks.
but if the user overrides that callback, he can use the raw ziplist or listpack as is, and also reduce the need / effort of unpacking them.

please note that what we recently added for modules callbacks (and even skip_object) can somewhat be considered the foundation of collecting the RESTORE payload (parsing just enough in order to buffer the bytes and know where to stop).

**Comment by sripathikrishnan** [comment]
Hi @oranagra - yes, I agree, okay to merge. 

Based on your previous comment, I am also adding a `start_raw_object` method to the callback. This method will get the key, expiry, and the raw bytes - similar to what the dump command would return (minus the checksum and rdb version). If this method is not defined, it will be a NoOp.

**Pull request merged**
